### PR TITLE
Fix to get all groups, not only the ones with active users

### PR DESCRIPTION
**Pull request by gerardba**
getting the group list from CCD website, also adding some debugging messages

I have no clue why GIT was unable to see that I only changed a few lines, the most significant one:
# 
# write out group file
# 

```
f=open("group","w")

# We get Groups from the list of all groups at the lab (CCD webpage)
keys = combined_gid_to_group_map.keys()
```

### CODE REVIEW

**Comment by gerardba** [comment]
please merge. I'm not sure why GIT diff thinks it's all changed; only changed ~5 lines. With MAC's diffmerge util it sees the changes.

**Comment by DmitryLitvintsev** [comment]
Gerard, to keep it clean please remove all commented out code that you added

**Comment by gerardba** [comment]
but that's "debug code" thats handy when debugging (which we will still
have to do a bit)....

I'm adding support for writing .json files now ^^

Gerard

2015-09-17 17:23 GMT-05:00 Dmitry Litvintsev notifications@github.com:

**Comment by DmitryLitvintsev** [comment]
it is commented out. Either introduce some debug switches (e.g. -debug option) or remove

**Comment by gerardba** [comment]
I've fixed it in my branch, I'm not sure if the pull request has moved with it or not, please take a look now you should see JSON support and a -v option for verbose/debug.

**Comment by DmitryLitvintsev** [comment]
Can you make another pull request?

**Pull request closed without merging**
